### ISSUE TITLE
Wrongly typed notes

### ISSUE THREAD

**Issue by gbergel** [jamescummings/SRO-ODD#23]
There are a few hundred `<note type='editorial'>s` that should have the @type="register" instead. 

See https://docs.google.com/spreadsheets/d/1O5VJH1nLJ3dFMCuZ5e_SKDIk3N_hBjrORwf7L9GbeoE/edit?usp=sharing

Could they be converted, please?

**Comment by jamescummings** [comment]
@gbergel 

hrmmm tricky,

The problem is that entries contain multiple `<note type="editorial">` appear in any entry.  I only checked a couple.... If I knew which number (of a count of notes in that record) it was (note1, note3, note5...) then it would be possible.  But retrieving that information is as much work as just changing them manually.

Another approach would be for me to produce a full list of editorial notes that had this information and then you delete the ones from the list that are correctly typed.  That again might takes as much work.
